(() => {
  if (new URLSearchParams(location.search).get('lang') !== 'en') return;
  const dictionaries = {
    'uart_explainer_73s.zh.html': [
      ['UART 异步通信｜73 秒动画','UART Explained | 73-second animation'],['RDK 小课堂 · UART','RDK MINI LESSON · UART'],['UART 没有时钟线','UART has no clock line'],['没有时钟线','has no clock line'],['两个乐手没有人打拍子，只能在开始前约好同一个速度。UART 把这个速度叫作波特率。','Like two musicians without a conductor, both devices agree on the tempo first. UART calls that tempo the baud rate.'],['乐手 A','Musician A'],['乐手 B','Musician B'],['一个字节，打包成一帧','One byte becomes one frame'],['起始位开头，8 位数据居中，停止位收尾。线路按位发送。','A start bit opens the frame, eight data bits follow, and a stop bit closes it.'],['低位先发','Least significant bit first'],['8N1：8 数据位，无校验，1 停止位','8N1: 8 data bits, no parity, 1 stop bit'],['打包和拆包由硬件完成','Hardware builds and reads each frame'],['程序只需要写入字节，UART 外设负责生成起始位、数据位和停止位。','Your program writes bytes. The UART peripheral handles every start, data, and stop bit.'],['程序写入','Program writes'],['UART 外设','UART peripheral'],['线路发送','Serial line'],['两端参数必须完全一致','Both ends need identical settings'],['波特率、数据位、校验位或停止位错一项，接收端就会在错误的位置采样。','A mismatch in baud rate, data bits, parity, or stop bits makes the receiver sample at the wrong time.'],['发送端','Transmitter'],['接收端','Receiver'],['✓ 采样位置一致','✓ Sampling stays aligned'],['参数不一致','Settings do not match'],['TX 与 RX 交叉，并且共地','Cross TX and RX, then connect ground'],['我的发送接你的接收。GND 为两端信号建立同一个电压参考。','My transmit pin connects to your receive pin. GND gives both devices the same voltage reference.'],['串口外设','UART device'],['接收','Receive'],['发送','Transmit'],['参考地','Common ground'],['RDK X5 的 UART1','UART1 on the RDK X5'],['8 号管脚发送，10 号管脚接收。Linux 设备节点为 /dev/ttyS1。','Pin 8 transmits and Pin 10 receives. Linux exposes the port as /dev/ttyS1.'],['8 号管脚Transmit，10 号管脚Receive。Linux 设备节点为 /dev/ttyS1。','Pin 8 transmits and Pin 10 receives. Linux exposes the port as /dev/ttyS1.'],['RDK X5 40pin 功能对照表','RDK X5 40-pin header diagram'],['× /dev/ttyS0 系统调试口','× /dev/ttyS0 system debug console'],['40pin UART 使用 3.3V 电平','The 40-pin UART uses 3.3V logic'],['RDK X5 UART 正常信号电平','Normal RDK X5 UART signal level'],['输入最大耐压 3.46V','Maximum input voltage: 3.46V'],['不能直接接入 40pin UART','Never connect this directly'],['需要电平转换','Use a level shifter'],['5V 串口直接接入，可能永久损坏开发板。','A direct 5V UART connection can permanently damage the board.']
    ],
    'i2c_explainer_83s.zh.html': [
      ['I2C 同步通信｜83 秒动画','I2C Explained | 83-second animation'],['RDK 小课堂 · I2C','RDK MINI LESSON · I2C'],['I2C 自带时钟线','I2C has a clock line'],['自带时钟线','has a clock line'],['SCL 打节拍，SDA 传数据。双方跟着同一个时钟工作，这就是同步通信。','SCL sets the timing and SDA carries the data. Both devices follow the same clock.'],['时钟','CLOCK'],['数据','DATA'],['统一节拍','ONE SHARED CLOCK'],['无需预先约定速度','NO SEPARATE BAUD RATE'],['一对总线挂多个设备','Many devices share the same bus'],['主机先喊地址。只有地址匹配的设备回应，其他设备继续等待。','The controller calls an address. Only the matching device responds.'],['主机点名','Controller calls'],['传感器','Sensor'],['OLED 屏','OLED display'],['扩展芯片','I/O expander'],['被点到的设备返回 ACK','The addressed device returns ACK'],['地址匹配后，从机拉低 SDA 回应“到”。主机收到 ACK，随后开始传数据。','The device pulls SDA low to acknowledge its address. Data transfer can then begin.'],['主机发送地址','Controller sends address'],['OLED 回应','OLED responds'],['i2cdetect 挨个地址点名','i2cdetect checks every address'],['挨个地址点名',' checks every address'],['扫描程序遍历总线地址，记录哪些设备返回 ACK。','The scan records every bus address that returns an ACK.'],['RDK X5 的两路 40pin I2C','Two I2C buses on the RDK X5 header'],['今天 OLED 接在 3、5 号管脚，因此 Linux 总线号使用 5。','Today the OLED uses Pins 3 and 5, so the Linux bus number is 5.'],['本次实验使用','USED IN THIS DEMO'],['OLED 接线只需要四根','The OLED needs four wires'],['供电使用 3.3V，数据线接入 I2C5。','Power comes from 3.3V. SDA and SCL connect to I2C5.'],['RDK X5 与 OLED 的 I2C 实物接线','Physical I2C wiring between the RDK X5 and OLED'],['先确认设备在线','Confirm the device is online first'],['运行扫描命令。结果出现 ','Run the bus scan. Seeing '],['，后面的代码才有通信基础。',' confirms that the OLED is ready to communicate.'],['设备在线 ✓','DEVICE ONLINE ✓'],['管脚功能异常时检查总线配置','Check the bus configuration if I2C is unavailable'],['在配置工具里确认 I2C 开关。修改配置后重启系统。','Enable I2C in the configuration tool, then restart the system.'],['进入总线配置','Open bus settings'],['保存设置','Save the setting'],['地址匹配后，从机拉低 SDA 回应“到”。主机收到 ACK，随后开始传DATA。','The device pulls SDA low to acknowledge its address. Data transfer can then begin.'],['供电使用 3.3V，DATA线接入 I2C5。','Power comes from 3.3V. SDA and SCL connect to I2C5.']
    ],
    'summary_explainer_17s.zh.html': [
      ['UART 与 I2C 课程总结｜17 秒动画','UART and I2C Recap | 17-second animation'],['RDK 小课堂 · UART / I2C','RDK MINI LESSON · UART / I2C'],['这就是本节课的全部内容','That wraps up this lesson'],['这就是本节课的','That wraps up '],['全部内容','this lesson'],['最后把 UART 和 I2C 各自最重要的两点记牢。','Here are the two details that matter most for each interface.'],['UART 与 I2C 的关键点','UART and I2C essentials'],['两端参数一致','Match both ends'],['TX 与 RX 交叉','Cross TX and RX'],['确认 Linux 总线号','Check the Linux bus'],['确认从机地址','Check the device address'],['完整接线表与代码','Complete wiring tables and code'],['配套讲义保留了实验所需的全部命令、接线和 Python 示例。','The course notes include every command, connection, and Python example used in the lab.'],['课程讲义','COURSE NOTES'],['实验代码','LAB CODE'],['我们下节课见。','See you in the next lesson.']
    ]
  };
  const name = location.pathname.split('/').pop();
  const replacements = dictionaries[name] || [];
  const walker = document.createTreeWalker(document.documentElement, NodeFilter.SHOW_TEXT);
  const nodes = [];
  while (walker.nextNode()) nodes.push(walker.currentNode);
  for (const node of nodes) {
    for (const [source, target] of replacements) node.nodeValue = node.nodeValue.split(source).join(target);
  }
  document.documentElement.lang = 'en';
})();
