(() => {
  if (new URLSearchParams(location.search).get('lang') !== 'en') return;
  const replacements = [
    ['RDK 小课堂 · 第 12 课','RDK MINI LESSON · LESSON 12'],
    ['40pin','40-pin header'],
    ['UART 与 I2C','UART and I2C'],
    ['从一根回环线开始，再接上四线 OLED。把 40pin 上最常用的两种通信接口跑通。','Start with a UART loopback, then connect a four-wire OLED. We will bring the two most useful interfaces on the 40-pin header to life.'],
    ['约 9 分钟','ABOUT 9 MIN'],
    ['本课使用的 40PIN 接口','40-PIN INTERFACES IN THIS LESSON'],
    ['今天要完成什么','TODAY’S GOAL'],
    ['这节课只做两件事','Two things to build'],
    ['GPIO 适合简单高低电平。连接串口模块或小屏幕，需要使用总线接口。','GPIO handles simple high and low signals. Serial modules and displays need a communication bus.'],
    ['01 / UART','01 / UART'],
    ['完成一次回环收发','Run a loopback test'],
    ['短接 Pin 8 与 Pin 10，确认发送的 AA55 能原样收到。','Short Pins 8 and 10, then confirm that every AA55 sent comes straight back.'],
    ['02 / I2C','02 / I2C'],
    ['扫描并点亮 OLED','Find and light the OLED'],
    ['在 I2C5 找到 0x3C，再让屏幕显示当前时间。','Find 0x3C on I2C5, then display the current time on the OLED.'],
    ['先说 UART','UART FIRST'],
    ['没有时钟线，就先约好参数','No clock line, so the settings must match'],
    ['UART 没有时钟线，通信双方必须提前约好相同参数。','UART has no clock line. Both devices must use the same settings before communication begins.'],
    ['波特率','BAUD RATE'],
    ['帧格式','FRAME FORMAT'],
    ['8N1：8 位数据 · 无校验 · 1 位停止位','8N1: 8 data bits · no parity · 1 stop bit'],
    ['接线规则','WIRING'],
    ['TX 接 RX，RX 接 TX，并且共地','Connect TX to RX and RX to TX, then connect ground'],
    ['40pin UART 是 3.3V 电平，输入最大耐压 3.46V；不要直连 5V 串口。','The 40-pin UART uses 3.3V logic. Its maximum input voltage is 3.46V. Never connect a 5V UART directly.'],
    ['UART1 接线','UART1 WIRING'],
    ['Pin 8 发，Pin 10 收','Pin 8 transmits. Pin 10 receives.'],
    ['RDK X5 的 40pin UART1 对应 /dev/ttyS1，/dev/ttyS0 是系统调试口。','Linux exposes UART1 on the 40-pin header as /dev/ttyS1. The system uses /dev/ttyS0 as its debug console.'],
    ['演示 01 · UART 回环','DEMO 01 · UART LOOPBACK'],
    ['看到收发一致，就说明链路通了','Matching Send and Recv confirms the link'],
    ['让串口自己对自己说话，先排除板端接口和参数问题。拔掉跳线后，接收应为空。','Send the UART output back into its own input to test the port and settings. Recv should be empty after removing the jumper.'],
    ['再说 I2C','NOW I2C'],
    ['I2C 用地址完成点名','I2C calls each device by address'],
    ['SCL 提供时钟节拍，SDA 逐位传输数据，多个设备可以共享同一组线。','SCL provides the clock and SDA carries the data. Several devices can share the same two lines.'],
    ['主机 · I2C5','CONTROLLER · I2C5'],
    ['从机 · 0x3C','DEVICE · 0x3C'],
    ['OLED 接线','OLED WIRING'],
    ['OLED 只需要四根线','The OLED needs four wires'],
    ['本课使用 I2C5。先断电接线，再启动开发板扫描地址。','This lesson uses I2C5. Power the board off before wiring, then start it and scan the bus.'],
    ['RDK X5 物理管脚','RDK X5 PIN'],
    ['作用','FUNCTION'],
    ['3.3V 供电','3.3V POWER'],
    ['共同参考地','COMMON GROUND'],
    ['I2C5 数据线','I2C5 DATA'],
    ['I2C5 时钟线','I2C5 CLOCK'],
    ['演示 02 · 扫描设备地址','DEMO 02 · SCAN DEVICE ADDRESSES'],
    ['先扫到 3c，再运行代码','Find 3c before running the code'],
    ['i2cdetect 逐个地址发起通信，收到 ACK 的地址会显示在表格里。','i2cdetect checks every address and prints the ones that return an ACK.'],
    ['扫描 I2C5；看到 3c 表示 OLED 已应答。','Scans I2C5. Seeing 3c means the OLED responded.'],
    ['代码使用 port=5、address=0x3C。','The code uses port=5 and address=0x3C.'],
    ['OLED 点亮与排障','OLED OUTPUT AND TROUBLESHOOTING'],
    ['先看结果，再按链路排查','Check the result, then follow the signal path'],
    ['能否扫到 0x3C 或 0x3D','Does the scan show 0x3C or 0x3D?'],
    ['代码里的 port 是否为 5','Does the code use port 5?'],
    ['代码地址是否与扫描结果一致','Does the code address match the scan?'],
    ['主控是 SSD1306 还是 SH1106','Does the display use SSD1306 or SH1106?'],
    ['回顾','RECAP'],
    ['两个接口，各记住两个关键点','Two details for each interface'],
    ['完整接线表、代码和课后练习都在配套讲义与 GitHub 仓库中。','The course notes and GitHub repository include the complete wiring tables, code, and exercises.'],
    ['参数一致 · 收发交叉','Matching settings · crossed TX and RX'],
    ['总线号正确 · 设备地址匹配','Correct bus number · matching device address'],
    ['下一课：把传感器数据搬上这块屏幕。','NEXT LESSON · Put live sensor data on the display'],
    ['键盘：← / → / Space 切换页面','KEYBOARD · ← / → / SPACE TO NAVIGATE'],
    ['从一根回环线开始，再接上四线 OLED。把 40-pin header 上最常用的两种通信接口跑通。','Start with a UART loopback, then connect a four-wire OLED. We will bring the two most useful interfaces on the 40-pin header to life.'],
    ['本课使用的 40-PIN HEADER 接口','40-PIN INTERFACES IN THIS LESSON'],
    ['本课使用的 40-pin header 接口','40-PIN INTERFACES IN THIS LESSON'],
    ['40-pin header UART 是 3.3V 电平，输入最大耐压 3.46V；不要直连 5V 串口。','The 40-pin UART uses 3.3V logic. Its maximum input voltage is 3.46V. Never connect a 5V UART directly.'],
    ['RDK X5 的 40-pin header UART1 对应 /dev/ttyS1，/dev/ttyS0 是系统调试口。','Linux exposes UART1 on the 40-pin header as /dev/ttyS1. The system uses /dev/ttyS0 as its debug console.']
  ];
  const walker = document.createTreeWalker(document.documentElement, NodeFilter.SHOW_TEXT);
  const nodes = [];
  while (walker.nextNode()) nodes.push(walker.currentNode);
  for (const node of nodes) {
    for (const [source, target] of replacements) node.nodeValue = node.nodeValue.split(source).join(target);
  }
  document.title = 'RDK X5 40-pin Header | UART and I2C';
  document.documentElement.lang = 'en';
})();
